#!/bin/bash
# Instaweb 2.0 — Mirroring Compliance Monitor
# Checks that all sandbox files are mirrored to GitHub
# Run: bash scripts/monitor-mirror.sh

set -e

REPO_DIR="$HOME/instaweb-mirror"
REPORT_DIR="$REPO_DIR/docs/compliance-logs"
TIMESTAMP=$(date '+%Y%m%d-%H%M%S')
REPORT_FILE="$REPORT_DIR/compliance-$TIMESTAMP.md"

mkdir -p "$REPORT_DIR"
cd "$REPO_DIR"

echo "# Mirroring Compliance Report" > "$REPORT_FILE"
echo "**Generated:** $(date)" >> "$REPORT_FILE"
echo "**GitHub Remote:** https://github.com/dbcsec/Instaweb2.0.git" >> "$REPORT_FILE"
echo "**Branch:** agency-os" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 1. Pull latest from remote
echo "## 1. Checking Remote Sync Status" >> "$REPORT_FILE"
git fetch origin agency-os 2>&1
LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse origin/agency-os)

if [ "$LOCAL" = "$REMOTE" ]; then
    echo "✅ **OK** — Local is in sync with remote." >> "$REPORT_FILE"
else
    echo "⚠️ **WARNING** — Local ($LOCAL) differs from remote ($REMOTE)" >> "$REPORT_FILE"
    echo "Run: git push origin agency-os" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# 2. Check for uncommitted changes  
echo "## 2. Uncommitted Changes" >> "$REPORT_FILE"
UNCOMMITTED=$(git status --porcelain)
if [ -z "$UNCOMMITTED" ]; then
    echo "✅ **OK** — No uncommitted changes." >> "$REPORT_FILE"
else
    echo "⚠️ **UNCOMMITTED FILES FOUND:**" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "$UNCOMMITTED" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# 3. Check GitHub file listing
echo "## 3. GitHub Repository Structure" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
git ls-tree -r --name-only HEAD >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 4. Summary
echo "## 4. Summary" >> "$REPORT_FILE"
TOTAL_FILES=$(git ls-tree -r HEAD | wc -l)
echo "- **Total files mirrored:** $TOTAL_FILES" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Report generated by ops-optimizer compliance monitor*" >> "$REPORT_FILE"

# Add report to git
git add "$REPORT_FILE"
git commit -m "[docs] Compliance report $TIMESTAMP" --allow-empty
git push origin agency-os 2>/dev/null || true

echo "Report saved: $REPORT_FILE"